### ISSUE TITLE
Konceptualna analiza

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1902#1]
Izrada koncepta programskog proizvoda i osnovne arhitekture koja prikazuje osnovne komponente (aplikacije) i njihove veze.

**Comment by ppletes** [comment]
[https://app.zenhub.com/files/218518063/ecb8496a-ef4c-4d55-87f6-b20d513cbce6/download](https://app.zenhub.com/files/218518063/ecb8496a-ef4c-4d55-87f6-b20d513cbce6/download)

Poštovani prof. Stapić,

ovo je pdf analize. Molim Vas da pregledate pa javite, pošto su dečki napravili model baze i skicu aplikacije prema ovom pdf-u. U slučaju pogreške, da mogu svoje skice i modele ispraviti i staviti ovdje.

Lijepi pozdrav,
Paula

**Comment by ppletes** [comment]
Do kraja dana ću napraviti i drugi task s funkcionalnostima..

**Comment by ppletes** [comment]
1. KRATKI OPIS 
 
Programski proizvod se sastoji od mobilne aplikacije, web aplikacije i web servisa za osnovnu školu. Uloga proizvoda je da se radi provjera ponašanja učenika I njegovog pripadnog razreda. 
Unos ocjena i opisa te pregled moguće je obaviti putem mobilne aplikacije, dok se u web aplikaciji uz sve navedeno može i vršiti upravljanje unesenim podacima putem web servisa. 
Ocjenjivanje se može primijeniti kvantitativno i kvalitativno, tj. ocjenom od 1 do 5 i opisom. 

Po potrebi moguće je dodati još jedan modul u svrhu ocjenjivanja razreda kao što je zacrnjivanje kružića od lošeg – dobrog – odličnog ponašanja razreda. (opcionalno) 
 
2. ANALIZA 
 
2.1. Pogled 
 
Sučelje mobilne aplikacije sastoji se od sljedećih dijelova: 
1) Prijava/odjava ovlaštenih korisnika 
2) Ponašanje 
- odabir razreda/učitelja   
- raspored sati po tjednima    
- unos ocjena, opisa i učenika 
3) Pregled 
- izvještaji i grafovi (proizvoljni vremenski odsječak, mjesečni, tromjesečni i godišnji) 
 
Sučelje web aplikacije sastoji se od sljedećih dijelova: 
1) Prijava/odjava ovlaštenih korisnika 
2) Ponašanje 
- odabir razreda/učitelja   
- raspored sati po tjednima    
- unos ocjena, opisa i učenika 
3) Pregled 
- izvještaji i grafovi (proizvoljni vremenski odsječak, mjesečni, tromjesečni i godišnji) 
4) Upravljanje unesenim podacima o učiteljima, učenicima, predmetima i ocjenama 
 
 
3. ARHITEKTURA 
 
3.1. Alati skica 

Skica arhitekture je napravljena unutar web online alata Draw.io, ujedno kao i model baze podataka. Skica aplikacije će biti napravljena u online alatu Marvel. 
 
3.2. Skica arhitekture 
 
3.2.1. 
 
 ![arhitektura_1.png](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/11362938-2cf7-4652-8d94-a140e8336e04)
 
Aplikacija je instalirana na mobilnim uređajima (ili tablet) i stolnim računalima.  
Pristup aplikaciji imaju ovlašteni korisnici.  
Učitelji unose ocjene i ostale potrebne podatke putem uređaja, isti se pohranjuju u bazu putem web servisa. 
 
 
3.2.2.  
 
 ![arhitektura_cijeli_sustav.png](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/0c753b28-6a4d-488a-b697-9b7de12d3008)

Ovdje je prikazan drugačiji dizajn iste arhitekture pogledom na cijeli sustav. 
 
3.2.3.  
 
![arhitektura_2.png](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/7b3a1091-9d1e-494d-8d2b-6d52a6dfa0db)
 
 Na slici iznad moguće je pogledati detaljniji prikaz arhitekture prema razradi na određene dijelove aplikacije s obzirom na neke njene funkcionalnosti.  
Mobilna aplikacija sastoji se od korisničkog sučelja putem kojeg je moguć unos podataka poput ocjena, opisa i drugih zabilješki. Iste te podatke unesene tog trenutka ili odabirom nekog vremenskog intervala, moguće je pregledati ispisom izvještaja ili pregledom nekih grafičkih prikaza. 
Jednako vrijedi i za web aplikaciju uz razliku da je unutar web aplikacije omogućeno upravljanje podacima u smislu upravljanje unesenih učenika, učitelja, rasporeda i sl. 

Podaci se unose korisničkim sučeljem koje je spojeno preko web servisa na bazu. 

Radi lakše manipulacije podacima i iz razloga predostrožnosti obje aplikacije podatke unose i čitaju iz baze putem web servisa. Baza podataka služi za pohranu svih unesenih podataka.
