### ISSUE TITLE
Detaljan opis funkcionalnosti / Product backlog

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1902#2]
Izrada dokumenta s detaljnim opisom funkcionalnosti koji će ujedno postati i product backlog. Dokument bi trebao sadržavati sve funkcionalnosti web aplikacije, web servisa i mobilne aplikacije. U ovom dokumentu nije potrebno raditi detaljan strukturni dizajn pojedinih funkcionalnosti već samo njihov popis i opis.
 - [x] Popis funkcionalnosti web aplikacije
 - [x] Popis funkcionalnosti web servisa
 - [x] Popis funkcionalnosti mobilne aplikacije
 - [x] Veza funkcionalnosti na skice aplikacije (veza na #3)

**Comment by ppletes** [comment]
Ovdje se nalaze funkcionalnosti s opisom i skicom

Lp, Paula Pleteš

[https://app.zenhub.com/files/218518063/27a1befc-8fb5-42a4-9934-7c12e6841add/download](https://app.zenhub.com/files/218518063/27a1befc-8fb5-42a4-9934-7c12e6841add/download)

![Slika_1.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/6bf6c493-e32d-4394-b194-399f41df1e29)

![Slika_2.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/49215dfa-9bc6-4986-a9b0-cade7e042e19)

![Slika_3.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/0c5668bd-d43c-4fe1-ab3a-844e20ad42fd)

**Comment by ppletes** [comment]
1. SVRHA PROGRAMSKOG PROIZVODA 
 
Osnovna svrha programskog proizvodima je omogućiti učiteljima ocjenu ponašanja razreda nakon svakog sata nastave, te generirati izvješća o ponašanju razreda tijekom određenog vremenskog razdoblja. 
 
1.1. Opis osnovnog dijela 
 
Glavni dio aplikacije ujedno kao i osnovna svrha jest unos ocjena razreda s ostalim potrebnim podacima. Taj dio aplikacije izgleda u obliku rasporeda u kojem je potrebno unijeti podatke na slijedeći način: 
 
![prikaz_rasporeda.png](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/95a2d517-61e5-4647-93b0-9b3b3f31254d) 

Podaci koji se unose su: ocjena, opis, te eventualni odabir učenika ukoliko je to potrebno. Po rasporedu se može pomicati vremenski, pa s obzirom na to moguć je pregled prošloga tjedna, mjeseca ili godine. 
 
2. POPIS I OPIS FUNKCIONALNOSTI 
 
RESTful servisi omogućuju upis/čitanje baze. Podaci uneseni putem web servisa pohranjuju se u bazu podataka, odakle se mogu pozivati i njima upravljati. Web servisi su direktna poveznica između baze podataka te web i mobilne aplikacije. Svi podaci uneseni putem web i mobilne aplikacije upisuju se u bazu uz pomoć web servisa i jednako je kod obrnute situacije, tj. dohvaćanja podataka. 

![1.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/b572e251-afb8-44cf-a669-f446ba0db754)

![2.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/601d4fef-55d7-492e-8daf-4cde4817ffcf)

![3.jpg](https://images.zenhubusercontent.com/5dc067df71b66f00016da87f/de921d57-cb8a-4e39-959a-6aee3d5d9e1a)
