### ISSUE TITLE
Izrada aplikacijskih skica

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1902#3]
U fazi definiranja korisničkih zahtjeva, izrada aplikacijskih skica omogućuje bolje razumijevanje svih funkcionalnosti aplikacije. Potrebno je izraditi skice ekrana web i mobilne aplikacije.
 - [x] Izrada skica web aplikacije
 - [x] Izrada skica mobilne aplikacije
 - [x] Veza skica sa opisom iz backloga (vidi #2)
 - [x] Izrada interaktivnog prototipa mobilne aplikacije

**Comment by corlukantonio** [comment]
Na poveznicama ispod se nalaze prve verzije interaktivnih prototipa za web i mobilnu aplikaciju:
https://marvelapp.com/5d0ga84
https://marvelapp.com/jf724c9

**Comment by corlukantonio** [comment]
Druge verzije interaktivnih prototipa za web i mobilnu aplikaciju:
https://marvelapp.com/7j48hib
https://marvelapp.com/9j0824g
