### ISSUE TITLE
Model baze podataka

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1902#4]
Posljednji korak prije početka implementacije je izrada detaljnog modela baze podataka. Mobilna aplikacije će biti "always online" što znači da neće biti potrebno nikakve podatke pohranjivati u samu mobilnu aplikaciju, već će sve podatke trebati držati u centraliziranoj bazi podataka na serveru. Izrada početne, ali detaljne, verzije modela podataka omogućiti će potpuno razumijevanje planiranih aplikacijskih funkcionalnosti.

**Comment by luka-padezanin97** [comment]
![image.png](https://images.zenhubusercontent.com/5dbf32177a4d02000177a08e/ddf8101c-0c7c-42a3-9174-8ec0d37e5938)

Prva verzija ERA modela

**Comment by luka-padezanin97** [comment]
![image.png](https://images.zenhubusercontent.com/5dbf32177a4d02000177a08e/8b725f98-3f06-4498-acf3-329857c2d90b)

Druga verzija ERA modela

Tablica Predavanja je dodana kako bi se mogao napraviti raspored sati po kojemu se mogu pratiti predavanja unutar tekućeg tjedna, kao i već ocijenjena predavanja od prijašnjih tjedana.
Tablice Opis i Odgovorni su dodane kako bi se za svaku ocijenu moglo dodati više opisa, te više krivaca za svaki opis.
Naposlijetku, dodana je još tablica Razina_prava.
